# Generated by Django 2.0.7 on 2019-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
